"""Add revisions table

Revision ID: 3ff04172e5be
Revises: 97f5188f6576
Create Date: 2026-06-24 22:57:56.877672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff04172e5be'
down_revision: Union[str, Sequence[str], None] = '97f5188f6576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.String(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_concept_id'), 'revisions', ['concept_id'], unique=False)
    op.create_index(op.f('ix_revisions_id'), 'revisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_concept_id'), table_name='revisions')
    op.drop_table('revisions')
    # ### end Alembic commands ###
