"""add_classrooms_tables

Revision ID: 47dc22e20f51
Revises: bf605fab20d6
Create Date: 2026-07-27 19:13:30.959479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dc22e20f51'
down_revision: Union[str, Sequence[str], None] = 'bf605fab20d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_id'), 'classrooms', ['id'], unique=False)
    op.create_index(op.f('ix_classrooms_join_code'), 'classrooms', ['join_code'], unique=True)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('classroom_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_members_classroom_id'), 'classroom_members', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_members_id'), 'classroom_members', ['id'], unique=False)
    op.create_index(op.f('ix_classroom_members_student_id'), 'classroom_members', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classroom_members_student_id'), table_name='classroom_members')
    op.drop_index(op.f('ix_classroom_members_id'), table_name='classroom_members')
    op.drop_index(op.f('ix_classroom_members_classroom_id'), table_name='classroom_members')
    op.drop_table('classroom_members')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_join_code'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_id'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
