"""add_beta_feedback_and_exit_surveys

Revision ID: 4b853752ba25
Revises: a587fd214358
Create Date: 2026-06-28 14:59:30.272852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b853752ba25'
down_revision: Union[str, Sequence[str], None] = 'a587fd214358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beta_feedback_feedback_type'), 'beta_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_beta_feedback_id'), 'beta_feedback', ['id'], unique=False)
    op.create_table('exit_survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_survey_responses_id'), 'exit_survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exit_survey_responses_id'), table_name='exit_survey_responses')
    op.drop_table('exit_survey_responses')
    op.drop_index(op.f('ix_beta_feedback_id'), table_name='beta_feedback')
    op.drop_index(op.f('ix_beta_feedback_feedback_type'), table_name='beta_feedback')
    op.drop_table('beta_feedback')
    # ### end Alembic commands ###
