"""Add knowledge graph

Revision ID: 73fc493bf1db
Revises: a0d6c038fb95
Create Date: 2026-06-14 01:19:49.600107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fc493bf1db'
down_revision: Union[str, Sequence[str], None] = 'a0d6c038fb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('variables', sa.Integer(), nullable=True),
    sa.Column('data_types', sa.Integer(), nullable=True),
    sa.Column('loops', sa.Integer(), nullable=True),
    sa.Column('functions', sa.Integer(), nullable=True),
    sa.Column('collections', sa.Integer(), nullable=True),
    sa.Column('oop', sa.Integer(), nullable=True),
    sa.Column('exceptions', sa.Integer(), nullable=True),
    sa.Column('files', sa.Integer(), nullable=True),
    sa.Column('modules', sa.Integer(), nullable=True),
    sa.Column('algorithms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_knowledge_graph_id'), 'knowledge_graph', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_graph_id'), table_name='knowledge_graph')
    op.drop_table('knowledge_graph')
    # ### end Alembic commands ###
