"""add_claimed_to_quests_and_achievements

Revision ID: 97765e1c2d8c
Revises: 110aca7e7fb3
Create Date: 2026-07-26 22:48:46.282307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97765e1c2d8c'
down_revision: Union[str, Sequence[str], None] = '110aca7e7fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_progress', sa.Column('claimed', sa.Boolean(), nullable=True))
    op.add_column('quest_progress', sa.Column('claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_progress', 'claimed')
    op.drop_column('achievement_progress', 'claimed')
    # ### end Alembic commands ###
