"""Add tower progress

Revision ID: 97f5188f6576
Revises: 73fc493bf1db
Create Date: 2026-06-14 01:27:07.160257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f5188f6576'
down_revision: Union[str, Sequence[str], None] = '73fc493bf1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tower_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('max_floor', sa.Integer(), nullable=True),
    sa.Column('current_floor', sa.Integer(), nullable=True),
    sa.Column('resonance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tower_progress_id'), 'tower_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tower_progress_id'), table_name='tower_progress')
    op.drop_table('tower_progress')
    # ### end Alembic commands ###
