"""add_daily_login_fields

Revision ID: a587fd214358
Revises: 3ff04172e5be
Create Date: 2026-06-28 14:51:45.849119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a587fd214358'
down_revision: Union[str, Sequence[str], None] = '3ff04172e5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('daily_streak', sa.Integer(), nullable=True))
    op.add_column('user_stats', sa.Column('last_claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_stats', sa.Column('total_login_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'total_login_days')
    op.drop_column('user_stats', 'last_claimed_at')
    op.drop_column('user_stats', 'daily_streak')
    # ### end Alembic commands ###
