"""add_index_to_analytics_created_at

Revision ID: bb0b04b97dbe
Revises: 97765e1c2d8c
Create Date: 2026-07-26 22:50:38.912087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0b04b97dbe'
down_revision: Union[str, Sequence[str], None] = '97765e1c2d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analytics_events_created_at'), 'analytics_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_events_created_at'), table_name='analytics_events')
    # ### end Alembic commands ###
