"""add_fk_indexes_and_password_reset

Revision ID: c6903c7562ed
Revises: 47dc22e20f51
Create Date: 2026-07-27 19:48:18.254754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6903c7562ed'
down_revision: Union[str, Sequence[str], None] = '47dc22e20f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_otp', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_achievement_progress_user_id'), 'achievement_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_beta_feedback_user_id'), 'beta_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_bug_reports_user_id'), 'bug_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_challenge_progress_user_id'), 'challenge_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_exit_survey_responses_user_id'), 'exit_survey_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_lesson_feedback_user_id'), 'lesson_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_user_id'), 'lesson_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_conversations_user_id'), 'mentor_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_messages_conversation_id'), 'mentor_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_region_progress_user_id'), 'region_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_revisions_user_id'), 'revisions', ['user_id'], unique=False)
    op.create_index(op.f('ix_spaced_repetition_user_id'), 'spaced_repetition', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_index(op.f('ix_spaced_repetition_user_id'), table_name='spaced_repetition')
    op.drop_index(op.f('ix_revisions_user_id'), table_name='revisions')
    op.drop_index(op.f('ix_region_progress_user_id'), table_name='region_progress')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_mentor_messages_conversation_id'), table_name='mentor_messages')
    op.drop_index(op.f('ix_mentor_conversations_user_id'), table_name='mentor_conversations')
    op.drop_index(op.f('ix_lesson_progress_user_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_feedback_user_id'), table_name='lesson_feedback')
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_exit_survey_responses_user_id'), table_name='exit_survey_responses')
    op.drop_index(op.f('ix_challenge_progress_user_id'), table_name='challenge_progress')
    op.drop_index(op.f('ix_bug_reports_user_id'), table_name='bug_reports')
    op.drop_index(op.f('ix_beta_feedback_user_id'), table_name='beta_feedback')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_achievement_progress_user_id'), table_name='achievement_progress')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
